final List<Map<String, String>> employeeData = [
  {
    'name': 'Alicia Wang',
    'email': 'alicia@example.com',
    'position': 'Asistente médico',
    'department': 'Salud',
    'salary': '\$78,000',
    'status': 'activo',
  },
  {
    'name': 'David Lee',
    'email': 'david@example.com',
    'position': 'Cirujano',
    'department': 'Medicina',
    'salary': '\$75,000',
    'status': 'inactivo',
  },
  {
    'name': 'Emily Johnson',
    'email': 'emily@example.com',
    'position': 'Enfermera',
    'department': 'Salud',
    'salary': '\$88,000',
    'status': 'activo',
  },
  {
    'name': 'Jane Cooper',
    'email': 'jane@example.com',
    'position': 'Enfermera jefe',
    'department': 'Salud',
    'salary': '\$85,000',
    'status': 'activo',
  },
  {
    'name': 'Michael Roberts',
    'email': 'michael@example.com',
    'position': 'Doctor',
    'department': 'Medicina',
    'salary': '\$86,000',
    'status': 'activo',
  },
  {
    'name': 'Robert Chen',
    'email': 'robert@example.com',
    'position': 'Director Jefe',
    'department': 'Salud',
    'salary': '\$95,000',
    'status': 'activo',
  },
];
